name: CI

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js 18
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.x
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.25.0
          run_install: true
      - name: Build (Generate static files)
        run: pnpm generate
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
